name: CI Only (Test Server Code)

on:
  push:
    branches: [ main ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create virtualenv and install dependencies
      run: |
        cd server
        python -m venv .venvServer
        source .venvServer/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
      run: |
        cd server
        source .venvServer/bin/activate
        echo "FIREBASE_JSON is set: " ${{ env.FIREBASE_JSON != '' }}
        pytest tests/

#  deploy:
#    runs-on: ubuntu-latest
#    needs: test
#    if: github.ref == 'refs/heads/main'
#    
#    steps:
#    - uses: actions/checkout@v3
#    
#    - name: Set up Python
#      uses: actions/setup-python@v4
#      with:
#        python-version: '3.12'
#    
#    - name: Setup environment
#      env:
#        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
#        FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
#      run: |
#        cd server
#        # Create .env with real secrets
#        echo "FIREBASE_API_KEY=${{ secrets.FIREBASE_API_KEY }}" > .env
#        echo "FIREBASE_JSON=${{ secrets.FIREBASE_JSON }}" >> .env
#    
#    - name: Deploy to VM
#      run: |
#        # Setup SSH
#        echo "${{ secrets.VM_SSH_KEY }}" > ~/.ssh/id_rsa
#        chmod 600 ~/.ssh/id_rsa
#        echo "${{ secrets.VM_HOST_KEY }}" >> ~/.ssh/known_hosts
#        
#        # Stop previous server instance
#        ssh aakash_senthilnathan_gmail_c@34.125.143.141 "cd /home/server && (kill $(cat server.pid) || true) && rm -f server.pid"
#        
#        # Deploy new code
#        scp -r server/ aakash_senthilnathan_gmail_c@34.125.143.141:/home/server/
#        
#        # Start new server instance
#        ssh aakash_senthilnathan_gmail_c@34.125.143.141 "cd /home/server && chmod +x scripts/setup.sh && ./scripts/setup.sh"
