name: CI Only (Test Server Code)

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'server/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Create virtualenv and install dependencies
      run: |
        cd server
        python -m venv .venvServer
        source .venvServer/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_JSON: ${{ secrets.FIREBASE_JSON }}
      run: |
        cd server
        source .venvServer/bin/activate
        echo "FIREBASE_JSON is set: " ${{ env.FIREBASE_JSON != '' }}
        if [ -d tests ]; then pytest tests/; else echo "No tests directory, skipping pytest."; fi